FROM node:12.22.1-buster-slim

RUN apt-get update

RUN apt-get install -y --no-install-recommends \
    git \
    curl \
    ca-certificates \
    python3 \
    make \
    g++ \
    fontconfig \
    libvips-dev

RUN curl https://install.meteor.com/ | sh

RUN rm package-lock.json

RUN npm install sharp

RUN meteor npm install

RUN meteor npm build --allow-superuser

WORKDIR /app